version = 0.1
[default.deploy.parameters]
stack_name = "horizon-trust-bank-stack-eun1"
resolve_s3 = true
s3_prefix = "horizon-trust-bank-stack-eun1"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
